version: "3"

services:
  rdtclient:
    image: "rogerfar/rdtclient:latest"
    container_name: rdtclient
    restart: unless-stopped
    hostname: "rdtclient"
    volumes:
      - '/volumes/downloads/:/data/downloads'
      - '/volumes/docker/rdtclient/:/data/db'
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      private_network:
        ipv4_address: 10.2.0.10
  jackett:
    image: "linuxserver/jackett:latest"
    container_name: jackett
    restart: unless-stopped
    hostname: "jackett"
    volumes:
      - '/volumes/downloads/jackett:/data/downloads'
      - '/volumes/docker/jackett/config:/config'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - AUTO_UPDATE=true #optional
    networks:
      private_network:
        ipv4_address: 10.2.0.11
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: flaresolverr
    restart: unless-stopped
    hostname: "flaresolverr"
    environment:
      - LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    networks:
      private_network:
        ipv4_address: 10.2.0.12
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    restart: unless-stopped
    hostname: "sonarr"
    volumes:
      - '/volumes/series:/tv'
      - '/volumes/downloads:/downloads'
      - '/volumes/docker/sonarr/config:/config'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    networks:
      private_network:
        ipv4_address: 10.2.0.13
  plex:
    image: "linuxserver/plex:latest"
    container_name: plex
    restart: unless-stopped
    hostname: "plex"
    volumes:
      - '/volumes/downloads/sonarr:/tv'
      - '/volumes/downloads/radarr:/movies'
      - '/volumes/docker/plex/config:/config'
    environment:
      #- PLEX_CLAIM=
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Brussels
    networks:
      private_network:
        ipv4_address: 10.2.0.14
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    restart: unless-stopped
    hostname: "radarr"
    volumes:
      - '/volumes/movies:/movies'
      - '/volumes/downloads:/downloads'
      - '/volumes/docker/radarr/config:/config'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    networks:
      private_network:
        ipv4_address: 10.2.0.15
networks:
      private_network:
        external:
          name: servicewireguard_private_network